@startuml

' Copyright (c) 2025 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' <https://www.apache.org/licenses/LICENSE-2.0>
'
' SPDX-License-Identifier: Apache-2.0

interface Builder {
    type Output
    build() : Self::Output
}

' Also called "Node"
interface Runtime {
    type InstanceBuilder<I>
}

Interface RuntimeBuilder {
    load_config(&mut self, config: &Path): &mut Self
    build(self): Self::Runtime
}

Builder <|-- RuntimeBuilder : Builder::Output: Runtime
RuntimeBuilder ..> Runtime : builds

interface Deref
interface DerefMut
Deref <|-- DerefMut

interface Sample<T>
Deref <|-- Sample : Deref::Target=T

interface SampleMut<T> {
    type Sample: Sample<T>
    into_sample(self) : Sample
    send(self) : Result
}
DerefMut <|-- SampleMut : Deref::Target=T

interface SampleMaybeUninit<T> {
    type SampleMut: SampleMut<T>
    assume_init(self) : SampleMut
    write(self, data) : SampleMut
    as_mut_ptr(&mut self) : *mut T
}

SampleMaybeUninit ..> SampleMut : builds
Sample <.. SampleMut : builds

class sample::RuntimeImpl

Runtime <- RuntimeImpl

@enduml
