[package]
name = "simple_multi_binding_api_proposal"
version = "0.1.0"
edition = "2024"

[dependencies]
iceoryx2 = "*"
iceoryx2-bb-container = "*"
iceoryx2-bb-system-types = "*"
serde_json = "1.0.140"
serde = "*"
rumqttc = "0.24.0"
