# *******************************************************************************>
# Copyright (c) 2024 Contributors to the Eclipse Foundation
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
# SPDX-License-Identifier: Apache-2.0 #
# *******************************************************************************


# 
filegroup(
    name = "Ecu2",
    srcs = [
        "Ecu2Blackbox.cdepl",
        "Ecu2Blackbox.fcdl",
        "//platform/aas/mw/com/test/twoface/franca/interface:test_interface",
        "//platform/aas/tools/franca/deployment_specifications:someip",
    ],
    visibility = ["//platform/aas/mw/com/test/twoface:__subpackages__"],
)
