# *******************************************************************************>
# Copyright (c) 2024 Contributors to the Eclipse Foundation
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
# SPDX-License-Identifier: Apache-2.0 #
# *******************************************************************************


# 
#load("//platform/aas/tools/sctf/bazel_gen:sctf_gen.bzl", "py_sctf_test")

# These tests make use of setuid
# Right now SCTF framework do not supports it.
# This test will be enabled once SCTF frameworks supports it().
#py_sctf_test(
#    name = "proxy_restart_shall_not_affect_other_proxies_kill_test",
#    srcs = [
#        "__init__.py",
#        "partial_restart_proxy_restart_shall_not_affect_other_proxies_kill_test.py",
#         "partial_restart_proxy_restart_shall_not_affect_other_proxies_fixture.py",
#    ],
#    data = ["//platform/aas/mw/com/test/partial_restart/proxy_restart_shall_not_affect_other_proxies:proxy_restart_shall_not_affect_other_proxies-pkg"],
#    main = "partial_restart_proxy_restart_shall_not_affect_other_proxies.py",
#    module_root = "platform/aas/mw/com/test/partial_restart/proxy_restart_shall_not_affect_other_proxies/sct",
#)

#py_sctf_test(
#    name = "proxy_restart_shall_not_affect_other_proxies_graceful_test",
#    srcs = [
#        "__init__.py",
#        "partial_restart_proxy_restart_shall_not_affect_other_proxies_graceful_test.py",
#         "partial_restart_proxy_restart_shall_not_affect_other_proxies_fixture.py",
#    ],
#    data = ["//platform/aas/mw/com/test/partial_restart/proxy_restart_shall_not_affect_other_proxies:proxy_restart_shall_not_affect_other_proxies-pkg"],
#    main = "partial_restart_proxy_restart_shall_not_affect_other_proxies.py",
#    module_root = "platform/aas/mw/com/test/partial_restart/proxy_restart_shall_not_affect_other_proxies/sct",
#)
