# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

alias(
    name = "service",
    actual = "//platform/aas/mw/com/test/twoface/src:service",
)

alias(
    name = "service-pkg.tar",
    actual = "//platform/aas/mw/com/test/twoface/src:service-pkg.tar",
    visibility = [
        "//platform/aas/mw/com/test/twoface/sct:__pkg__",
        "//platform/aas/test/mw/com:__pkg__",
    ],
)

alias(
    name = "client",
    actual = "//platform/aas/mw/com/test/twoface/src:client",
)

alias(
    name = "client-pkg.tar",
    actual = "//platform/aas/mw/com/test/twoface/src:client-pkg.tar",
    visibility = [
        "//platform/aas/mw/com/test/twoface/sct:__pkg__",
        "//platform/aas/test/mw/com:__pkg__",
    ],
)
