# *******************************************************************************>
# Copyright (c) 2024 Contributors to the Eclipse Foundation
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
# SPDX-License-Identifier: Apache-2.0 #
# *******************************************************************************


# 
filegroup(
    name = "client_app",
    srcs = [
        "ClientApp.fcdl",
        "//platform/aas/mw/com/test/twoface/franca/interface:test_interface",
    ],
    visibility = ["//platform/aas/mw/com/test/twoface:__subpackages__"],
)

filegroup(
    name = "service_app",
    srcs = [
        "ServiceApp.fcdl",
        "//platform/aas/mw/com/test/twoface/franca/interface:test_interface",
    ],
    visibility = ["//platform/aas/mw/com/test/twoface:__subpackages__"],
)
